#!/bin/sh

# Make script halt if encountering an error, as opposed to the standard shell
# behavior of ingoring them
set -e

INPUT="${1}"

# Use a POSIX-friendly way to detect whether a command is installed
is_available() {
  command -v "${1}" > /dev/null 2>&1
}

if ! is_available "avconv"; then
  echo "FFmpeg needs to be installed to continue. Aborting."
  exit 1
fi

if [ -z "${INPUT}" ]; then
  echo "No file specified. Aborting."
  exit 1
fi

if [ ! -f "${INPUT}" ]; then
  echo "${INPUT} isn't a file. Aborting."
  exit 1
fi

MIMETYPE="$(file --mime-type ${INPUT})"
MIMETYPE="${MIMETYPE#* }"

# Use temporary directory with clean-up handler for safe creation of temp files
TEMP_DIR="$(mktemp -d)" || echo 1
trap 'rm -rf "${TEMP_DIR}"' EXIT

# Path for FFmpeg output, which will then be further processed
GFY="${TEMP_DIR}/temp.webm"

# If file is .webm, then simply extract the encoded video losslessly
if [ "${MIMETYPE}" = "video/webm" ]; then
  ffmpeg -i "${INPUT}" -loglevel panic -vcodec copy -an "${GFY}"
else
  echo "Not a supported filetype. Aborting."
  exit 1
fi
