#!/bin/bash

# Make script halt if encountering an error rather than of ingoring them
set -e

# Use a POSIX-friendly way to detect whether a command is installed
is_available() {
  command -v "${1}" > /dev/null 2>&1
}
